image: maven:3-jdk-11-slim

variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - chmod +x ./gradlew

stages:
  - test
  - deploy


build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew build 


test:
  stage: test
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew test 


deploy:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY    
