image: gradle:4.6-jdk8-alpine 

variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle


stages:
  - build
  - test
  - deploy

Build:
  stage: build 
  tags:
    - ugrad

  script: 
    - ./gradlew build 

Test: 
  stage: test 
  tags:
    - ugrad
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: ./**/TEST-*.xml

deploy:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY   


