image: gradle:4.6-jdk8-alpine 

variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew test 
  artifacts:
    when: always
    expire_in: 1 week
    reports:
        junit: ./**/TEST-*.xml
  when: always

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew build 

deploy_stage:
  stage: deploy
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY

deploy_prod:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY





