variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew test 

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - ./gradlew build 

deploy:
  stage: deploy
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY






