image: gradle:4.6-jdk8-alpine 

variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false" 

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle


stages:
  - build
  - test
  - deploy

Build:
  stage: build 
  tags:
    - ugrad
  script: 
    - ./gradlew build 

Test: 
  stage: test 
  tags:
    - ugrad
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: ./**/TEST-*.xml


deploy_stage:
  stage: deploy
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGE --api-key=$HEROKU_API_KEY

deploy_prod:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PROD --api-key=$HEROKU_API_KEY



